### ISSUE TITLE
Announce root permissions requirement

### ISSUE THREAD

**Issue by TPS** [Faerbit/android-crond#1]
@Faerbit Tried this from F-droid, but, when _run_, it says it needs root (& I'm not gonna just for this app).

- [ ] Please make sure app manifest requests root
- [ ] Please update F-droid description w/ that, too.

Thanks!

**Comment by Faerbit** [comment]
Thanks for checking out my app.

As far as I am aware [this](https://gitlab.com/fdroid/fdroiddata/commit/c17e9c34e8203533e4016b6ac3a180307683bfe7) commit accomplished that. I am unsure, of how to check if that metadata made it into the repos, and what to do about it if it didn't.

As for the app manifest, it seems the permission is [deprecated](http://su.chainfire.eu/#updates-permission).

**Comment by TPS** [comment]
If it's depreciated, then it can't hurt to include it.  I think F-droid still checks for it to show such details before install.

**Comment by Faerbit** [comment]
Actually, yes it can:
1) It is not a standard. Some super user implementation might not know how to handle this.
2) Even with the SuperSU implementation by Chainfire this can cause [problems](http://stackoverflow.com/questions/28539808/unknown-permission-android-permission-access-superuser-in-package-com-powervr-pv).
