### ISSUE TITLE
Exit with Error Code 127

### ISSUE THREAD

**Issue by philiprhoades** [Faerbit/android-crond#12]
Faerbit,

Thanks for this app - it is just what I needed because I didn't want to install BusyBox.

My simple script works from the command line but with this crontab:

  10 * * * * root /data/media/0/bin/db.sh

I get the above error message - how to debug?

Thanks,
Phil.

**Comment by Faerbit** [comment]
What is the `root` supposed to mean?

**Comment by philiprhoades** [comment]
On a Linux system that is the user who runs the cron job - the format of the crontab was supposed to be the same as a Linux / UNIX crontab?

**Comment by Faerbit** [comment]
I have never seen this before.
The format is like [this](https://en.wikipedia.org/wiki/Cron#Overview). Anything else is not supported.
All commands are executed by `root` per default by this app.
So you just need to remove `root` from your example and it should work fine.

**Comment by Faerbit** [comment]
I assume my advice solved your problem, if not please reopen the issue.

**Comment by philiprhoades** [comment]
@Faerbit ,

Yes, I removed the "root" and it worked properly.  The format I used is required for /etc/crontab ie for a system-wide crontab - your format is for personal crontabs . . since it was for user "root", I assumed it was the system-wide format that was required . .

Thanks!
